service: techies4good-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_PATH: "./:/opt/node_modules"
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_ACCESS_SECRET: ${env:JWT_ACCESS_SECRET}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
  region: ap-southeast-2
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline

package:
  include:
    - node_modules/.prisma/**
    - node_modules/@prisma/**
